package me.luliru.gateway.core.storager.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * ApplicationQa
 * Created by luliru on 2019-07-03.
 */
public class ApplicationQa implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.id
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.devep_id
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private Long devepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.app_name
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.app_key
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private String appKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.app_secret
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private String appSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.callback_url
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private String callbackUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.callback_format
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private Byte callbackFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.ins_tm
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private Date insTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_qa.upd_tm
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private Date updTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application_qa
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.id
     *
     * @return the value of application_qa.id
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.id
     *
     * @param id the value for application_qa.id
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.devep_id
     *
     * @return the value of application_qa.devep_id
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public Long getDevepId() {
        return devepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.devep_id
     *
     * @param devepId the value for application_qa.devep_id
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setDevepId(Long devepId) {
        this.devepId = devepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.app_name
     *
     * @return the value of application_qa.app_name
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.app_name
     *
     * @param appName the value for application_qa.app_name
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.app_key
     *
     * @return the value of application_qa.app_key
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.app_key
     *
     * @param appKey the value for application_qa.app_key
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.app_secret
     *
     * @return the value of application_qa.app_secret
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.app_secret
     *
     * @param appSecret the value for application_qa.app_secret
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.callback_url
     *
     * @return the value of application_qa.callback_url
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.callback_url
     *
     * @param callbackUrl the value for application_qa.callback_url
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.callback_format
     *
     * @return the value of application_qa.callback_format
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public Byte getCallbackFormat() {
        return callbackFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.callback_format
     *
     * @param callbackFormat the value for application_qa.callback_format
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setCallbackFormat(Byte callbackFormat) {
        this.callbackFormat = callbackFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.ins_tm
     *
     * @return the value of application_qa.ins_tm
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public Date getInsTm() {
        return insTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.ins_tm
     *
     * @param insTm the value for application_qa.ins_tm
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setInsTm(Date insTm) {
        this.insTm = insTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_qa.upd_tm
     *
     * @return the value of application_qa.upd_tm
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public Date getUpdTm() {
        return updTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_qa.upd_tm
     *
     * @param updTm the value for application_qa.upd_tm
     *
     * @mbg.generated Mon Dec 17 16:59:07 CST 2018
     */
    public void setUpdTm(Date updTm) {
        this.updTm = updTm;
    }
}
